package com.zrt.zenb.entity;

public class PMsgMail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.OnlyID
     *
     * @mbg.generated
     */
    private String onlyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.DeviceID
     *
     * @mbg.generated
     */
    private String deviceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.PID
     *
     * @mbg.generated
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.ClientIP
     *
     * @mbg.generated
     */
    private String clientip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.ClientPort
     *
     * @mbg.generated
     */
    private Integer clientport;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.ServerIP
     *
     * @mbg.generated
     */
    private String serverip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.ServerPort
     *
     * @mbg.generated
     */
    private Integer serverport;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.timestamp
     *
     * @mbg.generated
     */
    private Integer timestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.EntityFileName
     *
     * @mbg.generated
     */
    private String entityfilename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.pcapFile
     *
     * @mbg.generated
     */
    private String pcapfile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.sOnlyID
     *
     * @mbg.generated
     */
    private String sonlyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.Date
     *
     * @mbg.generated
     */
    private String date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.strMailFrom
     *
     * @mbg.generated
     */
    private String strmailfrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.Mailid
     *
     * @mbg.generated
     */
    private String mailid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.strFrom
     *
     * @mbg.generated
     */
    private String strfrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.strTo
     *
     * @mbg.generated
     */
    private String strto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.RES0
     *
     * @mbg.generated
     */
    private String res0;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.RES1
     *
     * @mbg.generated
     */
    private String res1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.strSubject
     *
     * @mbg.generated
     */
    private String strsubject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.MainFileName
     *
     * @mbg.generated
     */
    private String mainfilename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.szTxtMainFileName
     *
     * @mbg.generated
     */
    private String sztxtmainfilename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.strSrcAttaName
     *
     * @mbg.generated
     */
    private String strsrcattaname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.strAttaFileName
     *
     * @mbg.generated
     */
    private String strattafilename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.strTxtAttaFileName
     *
     * @mbg.generated
     */
    private String strtxtattafilename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.szHeadFileName
     *
     * @mbg.generated
     */
    private String szheadfilename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.nAffixType
     *
     * @mbg.generated
     */
    private String naffixtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.AntiproxyType
     *
     * @mbg.generated
     */
    private Integer antiproxytype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.strMailType
     *
     * @mbg.generated
     */
    private String strmailtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.strUsername
     *
     * @mbg.generated
     */
    private String strusername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.strTmpPassword
     *
     * @mbg.generated
     */
    private String strtmppassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.nIsComplete
     *
     * @mbg.generated
     */
    private Integer niscomplete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.nOpType
     *
     * @mbg.generated
     */
    private Integer noptype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.nMultiSend
     *
     * @mbg.generated
     */
    private Integer nmultisend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.strLable
     *
     * @mbg.generated
     */
    private String strlable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.BehaveType
     *
     * @mbg.generated
     */
    private Integer behavetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.AppType
     *
     * @mbg.generated
     */
    private Integer apptype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.OpType
     *
     * @mbg.generated
     */
    private Integer optype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.id
     *
     * @return the value of t_mail.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.id
     *
     * @param id the value for t_mail.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.OnlyID
     *
     * @return the value of t_mail.OnlyID
     *
     * @mbg.generated
     */
    public String getOnlyid() {
        return onlyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.OnlyID
     *
     * @param onlyid the value for t_mail.OnlyID
     *
     * @mbg.generated
     */
    public void setOnlyid(String onlyid) {
        this.onlyid = onlyid == null ? null : onlyid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.DeviceID
     *
     * @return the value of t_mail.DeviceID
     *
     * @mbg.generated
     */
    public String getDeviceid() {
        return deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.DeviceID
     *
     * @param deviceid the value for t_mail.DeviceID
     *
     * @mbg.generated
     */
    public void setDeviceid(String deviceid) {
        this.deviceid = deviceid == null ? null : deviceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.PID
     *
     * @return the value of t_mail.PID
     *
     * @mbg.generated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.PID
     *
     * @param pid the value for t_mail.PID
     *
     * @mbg.generated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.ClientIP
     *
     * @return the value of t_mail.ClientIP
     *
     * @mbg.generated
     */
    public String getClientip() {
        return clientip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.ClientIP
     *
     * @param clientip the value for t_mail.ClientIP
     *
     * @mbg.generated
     */
    public void setClientip(String clientip) {
        this.clientip = clientip == null ? null : clientip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.ClientPort
     *
     * @return the value of t_mail.ClientPort
     *
     * @mbg.generated
     */
    public Integer getClientport() {
        return clientport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.ClientPort
     *
     * @param clientport the value for t_mail.ClientPort
     *
     * @mbg.generated
     */
    public void setClientport(Integer clientport) {
        this.clientport = clientport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.ServerIP
     *
     * @return the value of t_mail.ServerIP
     *
     * @mbg.generated
     */
    public String getServerip() {
        return serverip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.ServerIP
     *
     * @param serverip the value for t_mail.ServerIP
     *
     * @mbg.generated
     */
    public void setServerip(String serverip) {
        this.serverip = serverip == null ? null : serverip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.ServerPort
     *
     * @return the value of t_mail.ServerPort
     *
     * @mbg.generated
     */
    public Integer getServerport() {
        return serverport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.ServerPort
     *
     * @param serverport the value for t_mail.ServerPort
     *
     * @mbg.generated
     */
    public void setServerport(Integer serverport) {
        this.serverport = serverport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.timestamp
     *
     * @return the value of t_mail.timestamp
     *
     * @mbg.generated
     */
    public Integer getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.timestamp
     *
     * @param timestamp the value for t_mail.timestamp
     *
     * @mbg.generated
     */
    public void setTimestamp(Integer timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.EntityFileName
     *
     * @return the value of t_mail.EntityFileName
     *
     * @mbg.generated
     */
    public String getEntityfilename() {
        return entityfilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.EntityFileName
     *
     * @param entityfilename the value for t_mail.EntityFileName
     *
     * @mbg.generated
     */
    public void setEntityfilename(String entityfilename) {
        this.entityfilename = entityfilename == null ? null : entityfilename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.pcapFile
     *
     * @return the value of t_mail.pcapFile
     *
     * @mbg.generated
     */
    public String getPcapfile() {
        return pcapfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.pcapFile
     *
     * @param pcapfile the value for t_mail.pcapFile
     *
     * @mbg.generated
     */
    public void setPcapfile(String pcapfile) {
        this.pcapfile = pcapfile == null ? null : pcapfile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.sOnlyID
     *
     * @return the value of t_mail.sOnlyID
     *
     * @mbg.generated
     */
    public String getSonlyid() {
        return sonlyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.sOnlyID
     *
     * @param sonlyid the value for t_mail.sOnlyID
     *
     * @mbg.generated
     */
    public void setSonlyid(String sonlyid) {
        this.sonlyid = sonlyid == null ? null : sonlyid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.Date
     *
     * @return the value of t_mail.Date
     *
     * @mbg.generated
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.Date
     *
     * @param date the value for t_mail.Date
     *
     * @mbg.generated
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.strMailFrom
     *
     * @return the value of t_mail.strMailFrom
     *
     * @mbg.generated
     */
    public String getStrmailfrom() {
        return strmailfrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.strMailFrom
     *
     * @param strmailfrom the value for t_mail.strMailFrom
     *
     * @mbg.generated
     */
    public void setStrmailfrom(String strmailfrom) {
        this.strmailfrom = strmailfrom == null ? null : strmailfrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.Mailid
     *
     * @return the value of t_mail.Mailid
     *
     * @mbg.generated
     */
    public String getMailid() {
        return mailid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.Mailid
     *
     * @param mailid the value for t_mail.Mailid
     *
     * @mbg.generated
     */
    public void setMailid(String mailid) {
        this.mailid = mailid == null ? null : mailid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.strFrom
     *
     * @return the value of t_mail.strFrom
     *
     * @mbg.generated
     */
    public String getStrfrom() {
        return strfrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.strFrom
     *
     * @param strfrom the value for t_mail.strFrom
     *
     * @mbg.generated
     */
    public void setStrfrom(String strfrom) {
        this.strfrom = strfrom == null ? null : strfrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.strTo
     *
     * @return the value of t_mail.strTo
     *
     * @mbg.generated
     */
    public String getStrto() {
        return strto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.strTo
     *
     * @param strto the value for t_mail.strTo
     *
     * @mbg.generated
     */
    public void setStrto(String strto) {
        this.strto = strto == null ? null : strto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.RES0
     *
     * @return the value of t_mail.RES0
     *
     * @mbg.generated
     */
    public String getRes0() {
        return res0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.RES0
     *
     * @param res0 the value for t_mail.RES0
     *
     * @mbg.generated
     */
    public void setRes0(String res0) {
        this.res0 = res0 == null ? null : res0.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.RES1
     *
     * @return the value of t_mail.RES1
     *
     * @mbg.generated
     */
    public String getRes1() {
        return res1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.RES1
     *
     * @param res1 the value for t_mail.RES1
     *
     * @mbg.generated
     */
    public void setRes1(String res1) {
        this.res1 = res1 == null ? null : res1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.strSubject
     *
     * @return the value of t_mail.strSubject
     *
     * @mbg.generated
     */
    public String getStrsubject() {
        return strsubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.strSubject
     *
     * @param strsubject the value for t_mail.strSubject
     *
     * @mbg.generated
     */
    public void setStrsubject(String strsubject) {
        this.strsubject = strsubject == null ? null : strsubject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.MainFileName
     *
     * @return the value of t_mail.MainFileName
     *
     * @mbg.generated
     */
    public String getMainfilename() {
        return mainfilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.MainFileName
     *
     * @param mainfilename the value for t_mail.MainFileName
     *
     * @mbg.generated
     */
    public void setMainfilename(String mainfilename) {
        this.mainfilename = mainfilename == null ? null : mainfilename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.szTxtMainFileName
     *
     * @return the value of t_mail.szTxtMainFileName
     *
     * @mbg.generated
     */
    public String getSztxtmainfilename() {
        return sztxtmainfilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.szTxtMainFileName
     *
     * @param sztxtmainfilename the value for t_mail.szTxtMainFileName
     *
     * @mbg.generated
     */
    public void setSztxtmainfilename(String sztxtmainfilename) {
        this.sztxtmainfilename = sztxtmainfilename == null ? null : sztxtmainfilename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.strSrcAttaName
     *
     * @return the value of t_mail.strSrcAttaName
     *
     * @mbg.generated
     */
    public String getStrsrcattaname() {
        return strsrcattaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.strSrcAttaName
     *
     * @param strsrcattaname the value for t_mail.strSrcAttaName
     *
     * @mbg.generated
     */
    public void setStrsrcattaname(String strsrcattaname) {
        this.strsrcattaname = strsrcattaname == null ? null : strsrcattaname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.strAttaFileName
     *
     * @return the value of t_mail.strAttaFileName
     *
     * @mbg.generated
     */
    public String getStrattafilename() {
        return strattafilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.strAttaFileName
     *
     * @param strattafilename the value for t_mail.strAttaFileName
     *
     * @mbg.generated
     */
    public void setStrattafilename(String strattafilename) {
        this.strattafilename = strattafilename == null ? null : strattafilename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.strTxtAttaFileName
     *
     * @return the value of t_mail.strTxtAttaFileName
     *
     * @mbg.generated
     */
    public String getStrtxtattafilename() {
        return strtxtattafilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.strTxtAttaFileName
     *
     * @param strtxtattafilename the value for t_mail.strTxtAttaFileName
     *
     * @mbg.generated
     */
    public void setStrtxtattafilename(String strtxtattafilename) {
        this.strtxtattafilename = strtxtattafilename == null ? null : strtxtattafilename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.szHeadFileName
     *
     * @return the value of t_mail.szHeadFileName
     *
     * @mbg.generated
     */
    public String getSzheadfilename() {
        return szheadfilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.szHeadFileName
     *
     * @param szheadfilename the value for t_mail.szHeadFileName
     *
     * @mbg.generated
     */
    public void setSzheadfilename(String szheadfilename) {
        this.szheadfilename = szheadfilename == null ? null : szheadfilename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.nAffixType
     *
     * @return the value of t_mail.nAffixType
     *
     * @mbg.generated
     */
    public String getNaffixtype() {
        return naffixtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.nAffixType
     *
     * @param naffixtype the value for t_mail.nAffixType
     *
     * @mbg.generated
     */
    public void setNaffixtype(String naffixtype) {
        this.naffixtype = naffixtype == null ? null : naffixtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.AntiproxyType
     *
     * @return the value of t_mail.AntiproxyType
     *
     * @mbg.generated
     */
    public Integer getAntiproxytype() {
        return antiproxytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.AntiproxyType
     *
     * @param antiproxytype the value for t_mail.AntiproxyType
     *
     * @mbg.generated
     */
    public void setAntiproxytype(Integer antiproxytype) {
        this.antiproxytype = antiproxytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.strMailType
     *
     * @return the value of t_mail.strMailType
     *
     * @mbg.generated
     */
    public String getStrmailtype() {
        return strmailtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.strMailType
     *
     * @param strmailtype the value for t_mail.strMailType
     *
     * @mbg.generated
     */
    public void setStrmailtype(String strmailtype) {
        this.strmailtype = strmailtype == null ? null : strmailtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.strUsername
     *
     * @return the value of t_mail.strUsername
     *
     * @mbg.generated
     */
    public String getStrusername() {
        return strusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.strUsername
     *
     * @param strusername the value for t_mail.strUsername
     *
     * @mbg.generated
     */
    public void setStrusername(String strusername) {
        this.strusername = strusername == null ? null : strusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.strTmpPassword
     *
     * @return the value of t_mail.strTmpPassword
     *
     * @mbg.generated
     */
    public String getStrtmppassword() {
        return strtmppassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.strTmpPassword
     *
     * @param strtmppassword the value for t_mail.strTmpPassword
     *
     * @mbg.generated
     */
    public void setStrtmppassword(String strtmppassword) {
        this.strtmppassword = strtmppassword == null ? null : strtmppassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.nIsComplete
     *
     * @return the value of t_mail.nIsComplete
     *
     * @mbg.generated
     */
    public Integer getNiscomplete() {
        return niscomplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.nIsComplete
     *
     * @param niscomplete the value for t_mail.nIsComplete
     *
     * @mbg.generated
     */
    public void setNiscomplete(Integer niscomplete) {
        this.niscomplete = niscomplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.nOpType
     *
     * @return the value of t_mail.nOpType
     *
     * @mbg.generated
     */
    public Integer getNoptype() {
        return noptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.nOpType
     *
     * @param noptype the value for t_mail.nOpType
     *
     * @mbg.generated
     */
    public void setNoptype(Integer noptype) {
        this.noptype = noptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.nMultiSend
     *
     * @return the value of t_mail.nMultiSend
     *
     * @mbg.generated
     */
    public Integer getNmultisend() {
        return nmultisend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.nMultiSend
     *
     * @param nmultisend the value for t_mail.nMultiSend
     *
     * @mbg.generated
     */
    public void setNmultisend(Integer nmultisend) {
        this.nmultisend = nmultisend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.strLable
     *
     * @return the value of t_mail.strLable
     *
     * @mbg.generated
     */
    public String getStrlable() {
        return strlable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.strLable
     *
     * @param strlable the value for t_mail.strLable
     *
     * @mbg.generated
     */
    public void setStrlable(String strlable) {
        this.strlable = strlable == null ? null : strlable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.BehaveType
     *
     * @return the value of t_mail.BehaveType
     *
     * @mbg.generated
     */
    public Integer getBehavetype() {
        return behavetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.BehaveType
     *
     * @param behavetype the value for t_mail.BehaveType
     *
     * @mbg.generated
     */
    public void setBehavetype(Integer behavetype) {
        this.behavetype = behavetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.AppType
     *
     * @return the value of t_mail.AppType
     *
     * @mbg.generated
     */
    public Integer getApptype() {
        return apptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.AppType
     *
     * @param apptype the value for t_mail.AppType
     *
     * @mbg.generated
     */
    public void setApptype(Integer apptype) {
        this.apptype = apptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.OpType
     *
     * @return the value of t_mail.OpType
     *
     * @mbg.generated
     */
    public Integer getOptype() {
        return optype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.OpType
     *
     * @param optype the value for t_mail.OpType
     *
     * @mbg.generated
     */
    public void setOptype(Integer optype) {
        this.optype = optype;
    }
}
