package com.zrt.zenb.entity;

import com.zrt.zenb.entity.PMsgMail;

public interface PMsgMailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mail
     *
     * @mbg.generated
     */
    int insert(PMsgMail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mail
     *
     * @mbg.generated
     */
    int insertSelective(PMsgMail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mail
     *
     * @mbg.generated
     */
    PMsgMail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PMsgMail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PMsgMail record);
}
