package com.zrt.zenb.entity;

import java.util.List;
import java.util.Map;

import com.zrt.zenb.entity.PMsgHttp;

public interface PMsgHttpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_http
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_http
     *
     * @mbg.generated
     */
    int insert(PMsgHttp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_http
     *
     * @mbg.generated
     */
    int insertSelective(PMsgHttp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_http
     *
     * @mbg.generated
     */
    PMsgHttp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_http
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PMsgHttp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_http
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PMsgHttp record);
    
    List<PMsgHttp> selectHttpRecord(Map<String, Object> map);
}
