package com.zrt.zenb.entity;

import java.util.List;
import java.util.Map;

import com.zrt.zenb.entity.PMsgSms;

public interface PMsgSmsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms
     *
     * @mbg.generated
     */
    int insert(PMsgSms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms
     *
     * @mbg.generated
     */
    int insertSelective(PMsgSms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms
     *
     * @mbg.generated
     */
    PMsgSms selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PMsgSms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PMsgSms record);
    
    List<PMsgSms> selectSmsRecord(Map<String, Object> map);
}
