package com.zrt.zenb.entity;

import java.io.Serializable;

public class PMsgVoip extends MsgBase implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_voip.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_voip.OnlyID
     *
     * @mbg.generated
     */
    private String onlyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_voip.DeviceID
     *
     * @mbg.generated
     */
    private String deviceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_voip.PID
     *
     * @mbg.generated
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_voip.ClientIP
     *
     * @mbg.generated
     */
    private String clientip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_voip.ClientPort
     *
     * @mbg.generated
     */
    private Integer clientport;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_voip.ServerIP
     *
     * @mbg.generated
     */
    private String serverip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_voip.ServerPort
     *
     * @mbg.generated
     */
    private Integer serverport;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_voip.timestamp
     *
     * @mbg.generated
     */
    private Integer timestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_voip.EntityFileName
     *
     * @mbg.generated
     */
    private String entityfilename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_voip.pcapFile
     *
     * @mbg.generated
     */
    private String pcapfile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_voip.strRelateID
     *
     * @mbg.generated
     */
    private String strrelateid;
    
    private String strUsername;
    private String strPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_voip.strPhoneNum
     *
     * @mbg.generated
     */
    private String strphonenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_voip.strFromUsername
     *
     * @mbg.generated
     */
    private String strfromusername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_voip.strFromPhoneNum
     *
     * @mbg.generated
     */
    private String strfromphonenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_voip.strToUsername
     *
     * @mbg.generated
     */
    private String strtousername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_voip.strToPhoneNum
     *
     * @mbg.generated
     */
    private String strtophonenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_voip.nDataType
     *
     * @mbg.generated
     */
    private String ndatatype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_voip.szMainFileName
     *
     * @mbg.generated
     */
    private String szmainfilename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_voip.Status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_voip.OpType
     *
     * @mbg.generated
     */
    private Integer optype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_voip.CodecType
     *
     * @mbg.generated
     */
    private String codectype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_voip.ToolType
     *
     * @mbg.generated
     */
    private Integer tooltype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_voip.szPCapStartTime
     *
     * @mbg.generated
     */
    private Integer szpcapstarttime = 0;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_voip.szPCapEndTime
     *
     * @mbg.generated
     */
    private Integer szpcapendtime = 0;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_voip.id
     *
     * @return the value of t_voip.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_voip.id
     *
     * @param id the value for t_voip.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_voip.OnlyID
     *
     * @return the value of t_voip.OnlyID
     *
     * @mbg.generated
     */
    public String getOnlyid() {
        return onlyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_voip.OnlyID
     *
     * @param onlyid the value for t_voip.OnlyID
     *
     * @mbg.generated
     */
    public void setOnlyid(String onlyid) {
        this.onlyid = onlyid == null ? null : onlyid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_voip.DeviceID
     *
     * @return the value of t_voip.DeviceID
     *
     * @mbg.generated
     */
    public String getDeviceid() {
        return deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_voip.DeviceID
     *
     * @param deviceid the value for t_voip.DeviceID
     *
     * @mbg.generated
     */
    public void setDeviceid(String deviceid) {
        this.deviceid = deviceid == null ? null : deviceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_voip.PID
     *
     * @return the value of t_voip.PID
     *
     * @mbg.generated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_voip.PID
     *
     * @param pid the value for t_voip.PID
     *
     * @mbg.generated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_voip.ClientIP
     *
     * @return the value of t_voip.ClientIP
     *
     * @mbg.generated
     */
    public String getClientip() {
        return clientip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_voip.ClientIP
     *
     * @param clientip the value for t_voip.ClientIP
     *
     * @mbg.generated
     */
    public void setClientip(String clientip) {
        this.clientip = clientip == null ? null : clientip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_voip.ClientPort
     *
     * @return the value of t_voip.ClientPort
     *
     * @mbg.generated
     */
    public Integer getClientport() {
        return clientport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_voip.ClientPort
     *
     * @param clientport the value for t_voip.ClientPort
     *
     * @mbg.generated
     */
    public void setClientport(Integer clientport) {
        this.clientport = clientport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_voip.ServerIP
     *
     * @return the value of t_voip.ServerIP
     *
     * @mbg.generated
     */
    public String getServerip() {
        return serverip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_voip.ServerIP
     *
     * @param serverip the value for t_voip.ServerIP
     *
     * @mbg.generated
     */
    public void setServerip(String serverip) {
        this.serverip = serverip == null ? null : serverip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_voip.ServerPort
     *
     * @return the value of t_voip.ServerPort
     *
     * @mbg.generated
     */
    public Integer getServerport() {
        return serverport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_voip.ServerPort
     *
     * @param serverport the value for t_voip.ServerPort
     *
     * @mbg.generated
     */
    public void setServerport(Integer serverport) {
        this.serverport = serverport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_voip.timestamp
     *
     * @return the value of t_voip.timestamp
     *
     * @mbg.generated
     */
    public Integer getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_voip.timestamp
     *
     * @param timestamp the value for t_voip.timestamp
     *
     * @mbg.generated
     */
    public void setTimestamp(Integer timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_voip.EntityFileName
     *
     * @return the value of t_voip.EntityFileName
     *
     * @mbg.generated
     */
    public String getEntityfilename() {
        return entityfilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_voip.EntityFileName
     *
     * @param entityfilename the value for t_voip.EntityFileName
     *
     * @mbg.generated
     */
    public void setEntityfilename(String entityfilename) {
        this.entityfilename = entityfilename == null ? null : entityfilename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_voip.pcapFile
     *
     * @return the value of t_voip.pcapFile
     *
     * @mbg.generated
     */
    public String getPcapfile() {
        return pcapfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_voip.pcapFile
     *
     * @param pcapfile the value for t_voip.pcapFile
     *
     * @mbg.generated
     */
    public void setPcapfile(String pcapfile) {
        this.pcapfile = pcapfile == null ? null : pcapfile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_voip.strRelateID
     *
     * @return the value of t_voip.strRelateID
     *
     * @mbg.generated
     */
    public String getStrrelateid() {
        return strrelateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_voip.strRelateID
     *
     * @param strrelateid the value for t_voip.strRelateID
     *
     * @mbg.generated
     */
    public void setStrrelateid(String strrelateid) {
        this.strrelateid = strrelateid == null ? null : strrelateid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_voip.strPhoneNum
     *
     * @return the value of t_voip.strPhoneNum
     *
     * @mbg.generated
     */
    public String getStrphonenum() {
        return strphonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_voip.strPhoneNum
     *
     * @param strphonenum the value for t_voip.strPhoneNum
     *
     * @mbg.generated
     */
    public void setStrphonenum(String strphonenum) {
        this.strphonenum = strphonenum == null ? null : strphonenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_voip.strFromUsername
     *
     * @return the value of t_voip.strFromUsername
     *
     * @mbg.generated
     */
    public String getStrfromusername() {
        return strfromusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_voip.strFromUsername
     *
     * @param strfromusername the value for t_voip.strFromUsername
     *
     * @mbg.generated
     */
    public void setStrfromusername(String strfromusername) {
        this.strfromusername = strfromusername == null ? null : strfromusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_voip.strFromPhoneNum
     *
     * @return the value of t_voip.strFromPhoneNum
     *
     * @mbg.generated
     */
    public String getStrfromphonenum() {
        return strfromphonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_voip.strFromPhoneNum
     *
     * @param strfromphonenum the value for t_voip.strFromPhoneNum
     *
     * @mbg.generated
     */
    public void setStrfromphonenum(String strfromphonenum) {
        this.strfromphonenum = strfromphonenum == null ? null : strfromphonenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_voip.strToUsername
     *
     * @return the value of t_voip.strToUsername
     *
     * @mbg.generated
     */
    public String getStrtousername() {
        return strtousername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_voip.strToUsername
     *
     * @param strtousername the value for t_voip.strToUsername
     *
     * @mbg.generated
     */
    public void setStrtousername(String strtousername) {
        this.strtousername = strtousername == null ? null : strtousername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_voip.strToPhoneNum
     *
     * @return the value of t_voip.strToPhoneNum
     *
     * @mbg.generated
     */
    public String getStrtophonenum() {
        return strtophonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_voip.strToPhoneNum
     *
     * @param strtophonenum the value for t_voip.strToPhoneNum
     *
     * @mbg.generated
     */
    public void setStrtophonenum(String strtophonenum) {
        this.strtophonenum = strtophonenum == null ? null : strtophonenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_voip.nDataType
     *
     * @return the value of t_voip.nDataType
     *
     * @mbg.generated
     */
    public String getNdatatype() {
        return ndatatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_voip.nDataType
     *
     * @param ndatatype the value for t_voip.nDataType
     *
     * @mbg.generated
     */
    public void setNdatatype(String ndatatype) {
        this.ndatatype = ndatatype == null ? null : ndatatype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_voip.szMainFileName
     *
     * @return the value of t_voip.szMainFileName
     *
     * @mbg.generated
     */
    public String getSzmainfilename() {
        return szmainfilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_voip.szMainFileName
     *
     * @param szmainfilename the value for t_voip.szMainFileName
     *
     * @mbg.generated
     */
    public void setSzmainfilename(String szmainfilename) {
        this.szmainfilename = szmainfilename == null ? null : szmainfilename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_voip.Status
     *
     * @return the value of t_voip.Status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_voip.Status
     *
     * @param status the value for t_voip.Status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_voip.OpType
     *
     * @return the value of t_voip.OpType
     *
     * @mbg.generated
     */
    public Integer getOptype() {
        return optype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_voip.OpType
     *
     * @param optype the value for t_voip.OpType
     *
     * @mbg.generated
     */
    public void setOptype(Integer optype) {
        this.optype = optype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_voip.CodecType
     *
     * @return the value of t_voip.CodecType
     *
     * @mbg.generated
     */
    public String getCodectype() {
        return codectype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_voip.CodecType
     *
     * @param codectype the value for t_voip.CodecType
     *
     * @mbg.generated
     */
    public void setCodectype(String codectype) {
        this.codectype = codectype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_voip.ToolType
     *
     * @return the value of t_voip.ToolType
     *
     * @mbg.generated
     */
    public Integer getTooltype() {
        return tooltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_voip.ToolType
     *
     * @param tooltype the value for t_voip.ToolType
     *
     * @mbg.generated
     */
    public void setTooltype(Integer tooltype) {
        this.tooltype = tooltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_voip.szPCapStartTime
     *
     * @return the value of t_voip.szPCapStartTime
     *
     * @mbg.generated
     */
    public Integer getSzpcapstarttime() {
        return szpcapstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_voip.szPCapStartTime
     *
     * @param szpcapstarttime the value for t_voip.szPCapStartTime
     *
     * @mbg.generated
     */
    public void setSzpcapstarttime(Integer szpcapstarttime) {
        this.szpcapstarttime = szpcapstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_voip.szPCapEndTime
     *
     * @return the value of t_voip.szPCapEndTime
     *
     * @mbg.generated
     */
    public Integer getSzpcapendtime() {
        return szpcapendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_voip.szPCapEndTime
     *
     * @param szpcapendtime the value for t_voip.szPCapEndTime
     *
     * @mbg.generated
     */
    public void setSzpcapendtime(Integer szpcapendtime) {
        this.szpcapendtime = szpcapendtime;
    }
    
    public static final int fileContentsLen = 51;
    
    public PMsgVoip() {
    	
	}
    
    public PMsgVoip(String[] fileContents) {
    	int index = 0;

		onlyid = fileContents[index ++];
		deviceid = fileContents[index ++];
		index ++;
		try {
			pid = Integer.parseInt(fileContents[index ++]);
		}
		catch (Exception e) {
			e.printStackTrace();
		}
		clientip = fileContents[index ++];
		try {
			clientport = Integer.parseInt(fileContents[index ++]);
		}
		catch (Exception e) {
			e.printStackTrace();
		}
		index ++;
		serverip = fileContents[index ++];
		try {
			serverport = Integer.parseInt(fileContents[index ++]);
		}
		catch (Exception e) {
			e.printStackTrace();
		}
		index ++;
		index ++;
		try {
			timestamp = Integer.parseInt(fileContents[index ++]);
		}
		catch (Exception e) {
			e.printStackTrace();
		}
		index += 21;
		entityfilename = fileContents[index ++];
		pcapfile = fileContents[index ++];
		strrelateid = fileContents[index ++];
		
		strUsername = fileContents[index ++];
		strPassword = fileContents[index ++];
		
		strphonenum = fileContents[index ++];
		strfromusername = fileContents[index ++];
		strfromphonenum = fileContents[index ++];
		strtousername = fileContents[index ++];
		strtophonenum = fileContents[index ++];
		ndatatype = fileContents[index ++];
		szmainfilename = fileContents[index ++];
		String statusStr = fileContents[index ++];
		String optypeStr = fileContents[index ++];
		codectype = fileContents[index ++];
		String tooltypeStr = fileContents[index ++];
		String szpcapstarttimeStr = fileContents[index ++];
		String szpcapendtimeStr = fileContents[index ++];
		
		try {
			status = Integer.parseInt(statusStr);
		}
		catch (Exception e) {
//			e.printStackTrace();
			System.err.println("voip status parse to int exception.[" + statusStr + "]");
		}
		try {
			optype = Integer.parseInt(optypeStr);
		}
		catch (Exception e) {
//			e.printStackTrace();
			System.err.println("voip optype parse to int exception.[" + optypeStr + "]");
		}
		try {
			tooltype = Integer.parseInt(tooltypeStr);
		}
		catch (Exception e) {
//			e.printStackTrace();
			System.err.println("voip tooltype parse to int exception.[" + tooltypeStr + "]");
		}
		try {
			szpcapstarttime = Integer.parseInt(szpcapstarttimeStr);
		}
		catch (Exception e) {
//			e.printStackTrace();
			System.err.println("voip szpcapstarttime parse to int exception.[" + szpcapstarttimeStr + "]");
		}
		try {
			szpcapendtime = Integer.parseInt(szpcapendtimeStr);
		}
		catch (Exception e) {
//			e.printStackTrace();
			System.err.println("voip szpcapendtime parse to int exception.[" + szpcapendtimeStr + "]");
		}
    
    
    }
    
    private String userImsi;
    
	public String getUserImsi() {
		return userImsi;
	}

	public void setUserImsi(String userImsi) {
		this.userImsi = userImsi;
	}
}
