package com.zrt.zenb.entity;

import java.io.Serializable;

public class PMsgSms extends MsgBase implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms.OnlyID
     *
     * @mbg.generated
     */
    private String onlyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms.DeviceID
     *
     * @mbg.generated
     */
    private String deviceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms.PID
     *
     * @mbg.generated
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms.ClientIP
     *
     * @mbg.generated
     */
    private String clientip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms.ClientPort
     *
     * @mbg.generated
     */
    private Integer clientport;
    
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_sms.ClientMAC
    *
    * @mbg.generated
    */
   private String clientmac;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms.ServerIP
     *
     * @mbg.generated
     */
    private String serverip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms.ServerPort
     *
     * @mbg.generated
     */
    private Integer serverport;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_sms.ServerMAC
    *
    * @mbg.generated
    */
   private String servermac;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms.timestamp
     *
     * @mbg.generated
     */
    private Integer timestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms.EntityFileName
     *
     * @mbg.generated
     */
    private String entityfilename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms.pcapFile
     *
     * @mbg.generated
     */
    private String pcapfile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms.strPhoneNum
     *
     * @mbg.generated
     */
    private String strphonenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms.strFromUsername
     *
     * @mbg.generated
     */
    private String strfromusername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms.strFromPhoneNum
     *
     * @mbg.generated
     */
    private String strfromphonenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms.strToUsername
     *
     * @mbg.generated
     */
    private String strtousername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms.strToPhoneNum
     *
     * @mbg.generated
     */
    private String strtophonenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms.strContent
     *
     * @mbg.generated
     */
    private String strcontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms.nFragCount
     *
     * @mbg.generated
     */
    private Integer nfragcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms.nFragIndex
     *
     * @mbg.generated
     */
    private Integer nfragindex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms.szMainFileName
     *
     * @mbg.generated
     */
    private String szmainfilename;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms.id
     *
     * @return the value of t_sms.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms.id
     *
     * @param id the value for t_sms.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms.OnlyID
     *
     * @return the value of t_sms.OnlyID
     *
     * @mbg.generated
     */
    public String getOnlyid() {
        return onlyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms.OnlyID
     *
     * @param onlyid the value for t_sms.OnlyID
     *
     * @mbg.generated
     */
    public void setOnlyid(String onlyid) {
        this.onlyid = onlyid == null ? null : onlyid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms.DeviceID
     *
     * @return the value of t_sms.DeviceID
     *
     * @mbg.generated
     */
    public String getDeviceid() {
        return deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms.DeviceID
     *
     * @param deviceid the value for t_sms.DeviceID
     *
     * @mbg.generated
     */
    public void setDeviceid(String deviceid) {
        this.deviceid = deviceid == null ? null : deviceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms.PID
     *
     * @return the value of t_sms.PID
     *
     * @mbg.generated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms.PID
     *
     * @param pid the value for t_sms.PID
     *
     * @mbg.generated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms.ClientIP
     *
     * @return the value of t_sms.ClientIP
     *
     * @mbg.generated
     */
    public String getClientip() {
        return clientip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms.ClientIP
     *
     * @param clientip the value for t_sms.ClientIP
     *
     * @mbg.generated
     */
    public void setClientip(String clientip) {
        this.clientip = clientip == null ? null : clientip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms.ClientPort
     *
     * @return the value of t_sms.ClientPort
     *
     * @mbg.generated
     */
    public Integer getClientport() {
        return clientport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms.ClientPort
     *
     * @param clientport the value for t_sms.ClientPort
     *
     * @mbg.generated
     */
    public void setClientport(Integer clientport) {
        this.clientport = clientport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms.ServerIP
     *
     * @return the value of t_sms.ServerIP
     *
     * @mbg.generated
     */
    public String getServerip() {
        return serverip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms.ServerIP
     *
     * @param serverip the value for t_sms.ServerIP
     *
     * @mbg.generated
     */
    public void setServerip(String serverip) {
        this.serverip = serverip == null ? null : serverip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms.ServerPort
     *
     * @return the value of t_sms.ServerPort
     *
     * @mbg.generated
     */
    public Integer getServerport() {
        return serverport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms.ServerPort
     *
     * @param serverport the value for t_sms.ServerPort
     *
     * @mbg.generated
     */
    public void setServerport(Integer serverport) {
        this.serverport = serverport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms.timestamp
     *
     * @return the value of t_sms.timestamp
     *
     * @mbg.generated
     */
    public Integer getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms.timestamp
     *
     * @param timestamp the value for t_sms.timestamp
     *
     * @mbg.generated
     */
    public void setTimestamp(Integer timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms.EntityFileName
     *
     * @return the value of t_sms.EntityFileName
     *
     * @mbg.generated
     */
    public String getEntityfilename() {
        return entityfilename;
    }

    public String getClientmac() {
		return clientmac;
	}

	public void setClientmac(String clientmac) {
		this.clientmac = clientmac;
	}

	public String getServermac() {
		return servermac;
	}

	public void setServermac(String servermac) {
		this.servermac = servermac;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms.EntityFileName
     *
     * @param entityfilename the value for t_sms.EntityFileName
     *
     * @mbg.generated
     */
    public void setEntityfilename(String entityfilename) {
        this.entityfilename = entityfilename == null ? null : entityfilename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms.pcapFile
     *
     * @return the value of t_sms.pcapFile
     *
     * @mbg.generated
     */
    public String getPcapfile() {
        return pcapfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms.pcapFile
     *
     * @param pcapfile the value for t_sms.pcapFile
     *
     * @mbg.generated
     */
    public void setPcapfile(String pcapfile) {
        this.pcapfile = pcapfile == null ? null : pcapfile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms.strPhoneNum
     *
     * @return the value of t_sms.strPhoneNum
     *
     * @mbg.generated
     */
    public String getStrphonenum() {
        return strphonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms.strPhoneNum
     *
     * @param strphonenum the value for t_sms.strPhoneNum
     *
     * @mbg.generated
     */
    public void setStrphonenum(String strphonenum) {
        this.strphonenum = strphonenum == null ? null : strphonenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms.strFromUsername
     *
     * @return the value of t_sms.strFromUsername
     *
     * @mbg.generated
     */
    public String getStrfromusername() {
        return strfromusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms.strFromUsername
     *
     * @param strfromusername the value for t_sms.strFromUsername
     *
     * @mbg.generated
     */
    public void setStrfromusername(String strfromusername) {
        this.strfromusername = strfromusername == null ? null : strfromusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms.strFromPhoneNum
     *
     * @return the value of t_sms.strFromPhoneNum
     *
     * @mbg.generated
     */
    public String getStrfromphonenum() {
        return strfromphonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms.strFromPhoneNum
     *
     * @param strfromphonenum the value for t_sms.strFromPhoneNum
     *
     * @mbg.generated
     */
    public void setStrfromphonenum(String strfromphonenum) {
        this.strfromphonenum = strfromphonenum == null ? null : strfromphonenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms.strToUsername
     *
     * @return the value of t_sms.strToUsername
     *
     * @mbg.generated
     */
    public String getStrtousername() {
        return strtousername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms.strToUsername
     *
     * @param strtousername the value for t_sms.strToUsername
     *
     * @mbg.generated
     */
    public void setStrtousername(String strtousername) {
        this.strtousername = strtousername == null ? null : strtousername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms.strToPhoneNum
     *
     * @return the value of t_sms.strToPhoneNum
     *
     * @mbg.generated
     */
    public String getStrtophonenum() {
        return strtophonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms.strToPhoneNum
     *
     * @param strtophonenum the value for t_sms.strToPhoneNum
     *
     * @mbg.generated
     */
    public void setStrtophonenum(String strtophonenum) {
        this.strtophonenum = strtophonenum == null ? null : strtophonenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms.strContent
     *
     * @return the value of t_sms.strContent
     *
     * @mbg.generated
     */
    public String getStrcontent() {
        return strcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms.strContent
     *
     * @param strcontent the value for t_sms.strContent
     *
     * @mbg.generated
     */
    public void setStrcontent(String strcontent) {
        this.strcontent = strcontent == null ? null : strcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms.nFragCount
     *
     * @return the value of t_sms.nFragCount
     *
     * @mbg.generated
     */
    public Integer getNfragcount() {
        return nfragcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms.nFragCount
     *
     * @param nfragcount the value for t_sms.nFragCount
     *
     * @mbg.generated
     */
    public void setNfragcount(Integer nfragcount) {
        this.nfragcount = nfragcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms.nFragIndex
     *
     * @return the value of t_sms.nFragIndex
     *
     * @mbg.generated
     */
    public Integer getNfragindex() {
        return nfragindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms.nFragIndex
     *
     * @param nfragindex the value for t_sms.nFragIndex
     *
     * @mbg.generated
     */
    public void setNfragindex(Integer nfragindex) {
        this.nfragindex = nfragindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms.szMainFileName
     *
     * @return the value of t_sms.szMainFileName
     *
     * @mbg.generated
     */
    public String getSzmainfilename() {
        return szmainfilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms.szMainFileName
     *
     * @param szmainfilename the value for t_sms.szMainFileName
     *
     * @mbg.generated
     */
    public void setSzmainfilename(String szmainfilename) {
        this.szmainfilename = szmainfilename == null ? null : szmainfilename.trim();
    }
    
    public static final int fileContentsLen = 44;
    
    public PMsgSms() {
    	super();
    }
    
    public PMsgSms(String[] fileContents) {
    	int index = 0;

		onlyid = fileContents[index ++];
		deviceid = fileContents[index ++];
		index ++;
		try {
			pid = Integer.parseInt(fileContents[index ++]);
		}
		catch (Exception e) {
			e.printStackTrace();
		}
		clientip = fileContents[index ++];
		try {
			clientport = Integer.parseInt(fileContents[index ++]);
		}
		catch (Exception e) {
			e.printStackTrace();
		}
		clientmac = fileContents[index ++];
		serverip = fileContents[index ++];
		try {
			serverport = Integer.parseInt(fileContents[index ++]);
		}
		catch (Exception e) {
			e.printStackTrace();
		}
		servermac = fileContents[index ++];
		index ++;
		try {
			timestamp = Integer.parseInt(fileContents[index ++]);
		}
		catch (Exception e) {
			e.printStackTrace();
		}
		index += 21;
		entityfilename = fileContents[index ++];
		pcapfile = fileContents[index ++];
		strphonenum = fileContents[index ++];
		strfromusername = fileContents[index ++];
		strfromphonenum = fileContents[index ++];
		strtousername = fileContents[index ++];
		strtophonenum = fileContents[index ++];
		strcontent = fileContents[index ++];
		try {
			nfragcount = Integer.parseInt(fileContents[index ++]);
		}
		catch (Exception e) {
			e.printStackTrace();
		}
		try {
			nfragindex = Integer.parseInt(fileContents[index ++]);
		}
		catch (Exception e) {
			e.printStackTrace();
		}
		szmainfilename = fileContents[index ++];
    }

    private String userImsi;
    
	public String getUserImsi() {
		return userImsi;
	}

	public void setUserImsi(String userImsi) {
		this.userImsi = userImsi;
	}
    
}
