package com.zrt.zenb.entity;

import java.util.List;
import java.util.Map;

import com.zrt.zenb.entity.PMsgVoip;

public interface PMsgVoipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_voip
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_voip
     *
     * @mbg.generated
     */
    int insert(PMsgVoip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_voip
     *
     * @mbg.generated
     */
    int insertSelective(PMsgVoip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_voip
     *
     * @mbg.generated
     */
    PMsgVoip selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_voip
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PMsgVoip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_voip
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PMsgVoip record);
    
    List<PMsgVoip> selectVoipRecord(Map<String, Object> map);
}
