package com.zrt.zenb.entity;

public class PMsgHttp extends MsgBase {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_http.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_http.OnlyID
     *
     * @mbg.generated
     */
    private String onlyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_http.DeviceID
     *
     * @mbg.generated
     */
    private String deviceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_http.PID
     *
     * @mbg.generated
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_http.ClientIP
     *
     * @mbg.generated
     */
    private String clientip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_http.ClientPort
     *
     * @mbg.generated
     */
    private Integer clientport;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_http.ServerIP
     *
     * @mbg.generated
     */
    private String serverip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_http.ServerPort
     *
     * @mbg.generated
     */
    private Integer serverport;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_http.timestamp
     *
     * @mbg.generated
     */
    private Integer timestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_http.EntityFileName
     *
     * @mbg.generated
     */
    private String entityfilename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_http.pcapFile
     *
     * @mbg.generated
     */
    private String pcapfile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_http.strURL
     *
     * @mbg.generated
     */
    private String strurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_http.strMethod
     *
     * @mbg.generated
     */
    private String strmethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_http.strContentType
     *
     * @mbg.generated
     */
    private String strcontenttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_http.szMainFileName
     *
     * @mbg.generated
     */
    private String szmainfilename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_http.sztxtMainFileName
     *
     * @mbg.generated
     */
    private String sztxtmainfilename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_http.szPostFileName
     *
     * @mbg.generated
     */
    private String szpostfilename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_http.strAttaName
     *
     * @mbg.generated
     */
    private String strattaname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_http.strAttaFileName
     *
     * @mbg.generated
     */
    private String strattafilename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_http.strTxtAttaFileName
     *
     * @mbg.generated
     */
    private String strtxtattafilename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_http.AffixType
     *
     * @mbg.generated
     */
    private Integer affixtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_http.NetiProxyType
     *
     * @mbg.generated
     */
    private Integer netiproxytype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_http.strReferer
     *
     * @mbg.generated
     */
    private String strreferer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_http.strHost
     *
     * @mbg.generated
     */
    private String strhost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_http.strTitle
     *
     * @mbg.generated
     */
    private String strtitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_http.strCookie
     *
     * @mbg.generated
     */
    private String strcookie;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_http.IsComplete
     *
     * @mbg.generated
     */
    private Integer iscomplete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_http.strDomain
     *
     * @mbg.generated
     */
    private String strdomain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_http.szReserve
     *
     * @mbg.generated
     */
    private String szreserve;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_http.BehaveType
     *
     * @mbg.generated
     */
    private Integer behavetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_http.AppType
     *
     * @mbg.generated
     */
    private Integer apptype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_http.OpType
     *
     * @mbg.generated
     */
    private Integer optype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_http.id
     *
     * @return the value of t_http.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_http.id
     *
     * @param id the value for t_http.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_http.OnlyID
     *
     * @return the value of t_http.OnlyID
     *
     * @mbg.generated
     */
    public String getOnlyid() {
        return onlyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_http.OnlyID
     *
     * @param onlyid the value for t_http.OnlyID
     *
     * @mbg.generated
     */
    public void setOnlyid(String onlyid) {
        this.onlyid = onlyid == null ? null : onlyid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_http.DeviceID
     *
     * @return the value of t_http.DeviceID
     *
     * @mbg.generated
     */
    public String getDeviceid() {
        return deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_http.DeviceID
     *
     * @param deviceid the value for t_http.DeviceID
     *
     * @mbg.generated
     */
    public void setDeviceid(String deviceid) {
        this.deviceid = deviceid == null ? null : deviceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_http.PID
     *
     * @return the value of t_http.PID
     *
     * @mbg.generated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_http.PID
     *
     * @param pid the value for t_http.PID
     *
     * @mbg.generated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_http.ClientIP
     *
     * @return the value of t_http.ClientIP
     *
     * @mbg.generated
     */
    public String getClientip() {
        return clientip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_http.ClientIP
     *
     * @param clientip the value for t_http.ClientIP
     *
     * @mbg.generated
     */
    public void setClientip(String clientip) {
        this.clientip = clientip == null ? null : clientip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_http.ClientPort
     *
     * @return the value of t_http.ClientPort
     *
     * @mbg.generated
     */
    public Integer getClientport() {
        return clientport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_http.ClientPort
     *
     * @param clientport the value for t_http.ClientPort
     *
     * @mbg.generated
     */
    public void setClientport(Integer clientport) {
        this.clientport = clientport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_http.ServerIP
     *
     * @return the value of t_http.ServerIP
     *
     * @mbg.generated
     */
    public String getServerip() {
        return serverip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_http.ServerIP
     *
     * @param serverip the value for t_http.ServerIP
     *
     * @mbg.generated
     */
    public void setServerip(String serverip) {
        this.serverip = serverip == null ? null : serverip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_http.ServerPort
     *
     * @return the value of t_http.ServerPort
     *
     * @mbg.generated
     */
    public Integer getServerport() {
        return serverport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_http.ServerPort
     *
     * @param serverport the value for t_http.ServerPort
     *
     * @mbg.generated
     */
    public void setServerport(Integer serverport) {
        this.serverport = serverport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_http.timestamp
     *
     * @return the value of t_http.timestamp
     *
     * @mbg.generated
     */
    public Integer getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_http.timestamp
     *
     * @param timestamp the value for t_http.timestamp
     *
     * @mbg.generated
     */
    public void setTimestamp(Integer timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_http.EntityFileName
     *
     * @return the value of t_http.EntityFileName
     *
     * @mbg.generated
     */
    public String getEntityfilename() {
        return entityfilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_http.EntityFileName
     *
     * @param entityfilename the value for t_http.EntityFileName
     *
     * @mbg.generated
     */
    public void setEntityfilename(String entityfilename) {
        this.entityfilename = entityfilename == null ? null : entityfilename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_http.pcapFile
     *
     * @return the value of t_http.pcapFile
     *
     * @mbg.generated
     */
    public String getPcapfile() {
        return pcapfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_http.pcapFile
     *
     * @param pcapfile the value for t_http.pcapFile
     *
     * @mbg.generated
     */
    public void setPcapfile(String pcapfile) {
        this.pcapfile = pcapfile == null ? null : pcapfile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_http.strURL
     *
     * @return the value of t_http.strURL
     *
     * @mbg.generated
     */
    public String getStrurl() {
        return strurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_http.strURL
     *
     * @param strurl the value for t_http.strURL
     *
     * @mbg.generated
     */
    public void setStrurl(String strurl) {
        this.strurl = strurl == null ? null : strurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_http.strMethod
     *
     * @return the value of t_http.strMethod
     *
     * @mbg.generated
     */
    public String getStrmethod() {
        return strmethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_http.strMethod
     *
     * @param strmethod the value for t_http.strMethod
     *
     * @mbg.generated
     */
    public void setStrmethod(String strmethod) {
        this.strmethod = strmethod == null ? null : strmethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_http.strContentType
     *
     * @return the value of t_http.strContentType
     *
     * @mbg.generated
     */
    public String getStrcontenttype() {
        return strcontenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_http.strContentType
     *
     * @param strcontenttype the value for t_http.strContentType
     *
     * @mbg.generated
     */
    public void setStrcontenttype(String strcontenttype) {
        this.strcontenttype = strcontenttype == null ? null : strcontenttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_http.szMainFileName
     *
     * @return the value of t_http.szMainFileName
     *
     * @mbg.generated
     */
    public String getSzmainfilename() {
        return szmainfilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_http.szMainFileName
     *
     * @param szmainfilename the value for t_http.szMainFileName
     *
     * @mbg.generated
     */
    public void setSzmainfilename(String szmainfilename) {
        this.szmainfilename = szmainfilename == null ? null : szmainfilename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_http.sztxtMainFileName
     *
     * @return the value of t_http.sztxtMainFileName
     *
     * @mbg.generated
     */
    public String getSztxtmainfilename() {
        return sztxtmainfilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_http.sztxtMainFileName
     *
     * @param sztxtmainfilename the value for t_http.sztxtMainFileName
     *
     * @mbg.generated
     */
    public void setSztxtmainfilename(String sztxtmainfilename) {
        this.sztxtmainfilename = sztxtmainfilename == null ? null : sztxtmainfilename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_http.szPostFileName
     *
     * @return the value of t_http.szPostFileName
     *
     * @mbg.generated
     */
    public String getSzpostfilename() {
        return szpostfilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_http.szPostFileName
     *
     * @param szpostfilename the value for t_http.szPostFileName
     *
     * @mbg.generated
     */
    public void setSzpostfilename(String szpostfilename) {
        this.szpostfilename = szpostfilename == null ? null : szpostfilename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_http.strAttaName
     *
     * @return the value of t_http.strAttaName
     *
     * @mbg.generated
     */
    public String getStrattaname() {
        return strattaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_http.strAttaName
     *
     * @param strattaname the value for t_http.strAttaName
     *
     * @mbg.generated
     */
    public void setStrattaname(String strattaname) {
        this.strattaname = strattaname == null ? null : strattaname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_http.strAttaFileName
     *
     * @return the value of t_http.strAttaFileName
     *
     * @mbg.generated
     */
    public String getStrattafilename() {
        return strattafilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_http.strAttaFileName
     *
     * @param strattafilename the value for t_http.strAttaFileName
     *
     * @mbg.generated
     */
    public void setStrattafilename(String strattafilename) {
        this.strattafilename = strattafilename == null ? null : strattafilename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_http.strTxtAttaFileName
     *
     * @return the value of t_http.strTxtAttaFileName
     *
     * @mbg.generated
     */
    public String getStrtxtattafilename() {
        return strtxtattafilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_http.strTxtAttaFileName
     *
     * @param strtxtattafilename the value for t_http.strTxtAttaFileName
     *
     * @mbg.generated
     */
    public void setStrtxtattafilename(String strtxtattafilename) {
        this.strtxtattafilename = strtxtattafilename == null ? null : strtxtattafilename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_http.AffixType
     *
     * @return the value of t_http.AffixType
     *
     * @mbg.generated
     */
    public Integer getAffixtype() {
        return affixtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_http.AffixType
     *
     * @param affixtype the value for t_http.AffixType
     *
     * @mbg.generated
     */
    public void setAffixtype(Integer affixtype) {
        this.affixtype = affixtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_http.NetiProxyType
     *
     * @return the value of t_http.NetiProxyType
     *
     * @mbg.generated
     */
    public Integer getNetiproxytype() {
        return netiproxytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_http.NetiProxyType
     *
     * @param netiproxytype the value for t_http.NetiProxyType
     *
     * @mbg.generated
     */
    public void setNetiproxytype(Integer netiproxytype) {
        this.netiproxytype = netiproxytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_http.strReferer
     *
     * @return the value of t_http.strReferer
     *
     * @mbg.generated
     */
    public String getStrreferer() {
        return strreferer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_http.strReferer
     *
     * @param strreferer the value for t_http.strReferer
     *
     * @mbg.generated
     */
    public void setStrreferer(String strreferer) {
        this.strreferer = strreferer == null ? null : strreferer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_http.strHost
     *
     * @return the value of t_http.strHost
     *
     * @mbg.generated
     */
    public String getStrhost() {
        return strhost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_http.strHost
     *
     * @param strhost the value for t_http.strHost
     *
     * @mbg.generated
     */
    public void setStrhost(String strhost) {
        this.strhost = strhost == null ? null : strhost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_http.strTitle
     *
     * @return the value of t_http.strTitle
     *
     * @mbg.generated
     */
    public String getStrtitle() {
        return strtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_http.strTitle
     *
     * @param strtitle the value for t_http.strTitle
     *
     * @mbg.generated
     */
    public void setStrtitle(String strtitle) {
        this.strtitle = strtitle == null ? null : strtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_http.strCookie
     *
     * @return the value of t_http.strCookie
     *
     * @mbg.generated
     */
    public String getStrcookie() {
        return strcookie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_http.strCookie
     *
     * @param strcookie the value for t_http.strCookie
     *
     * @mbg.generated
     */
    public void setStrcookie(String strcookie) {
        this.strcookie = strcookie == null ? null : strcookie.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_http.IsComplete
     *
     * @return the value of t_http.IsComplete
     *
     * @mbg.generated
     */
    public Integer getIscomplete() {
        return iscomplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_http.IsComplete
     *
     * @param iscomplete the value for t_http.IsComplete
     *
     * @mbg.generated
     */
    public void setIscomplete(Integer iscomplete) {
        this.iscomplete = iscomplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_http.strDomain
     *
     * @return the value of t_http.strDomain
     *
     * @mbg.generated
     */
    public String getStrdomain() {
        return strdomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_http.strDomain
     *
     * @param strdomain the value for t_http.strDomain
     *
     * @mbg.generated
     */
    public void setStrdomain(String strdomain) {
        this.strdomain = strdomain == null ? null : strdomain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_http.szReserve
     *
     * @return the value of t_http.szReserve
     *
     * @mbg.generated
     */
    public String getSzreserve() {
        return szreserve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_http.szReserve
     *
     * @param szreserve the value for t_http.szReserve
     *
     * @mbg.generated
     */
    public void setSzreserve(String szreserve) {
        this.szreserve = szreserve == null ? null : szreserve.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_http.BehaveType
     *
     * @return the value of t_http.BehaveType
     *
     * @mbg.generated
     */
    public Integer getBehavetype() {
        return behavetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_http.BehaveType
     *
     * @param behavetype the value for t_http.BehaveType
     *
     * @mbg.generated
     */
    public void setBehavetype(Integer behavetype) {
        this.behavetype = behavetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_http.AppType
     *
     * @return the value of t_http.AppType
     *
     * @mbg.generated
     */
    public Integer getApptype() {
        return apptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_http.AppType
     *
     * @param apptype the value for t_http.AppType
     *
     * @mbg.generated
     */
    public void setApptype(Integer apptype) {
        this.apptype = apptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_http.OpType
     *
     * @return the value of t_http.OpType
     *
     * @mbg.generated
     */
    public Integer getOptype() {
        return optype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_http.OpType
     *
     * @param optype the value for t_http.OpType
     *
     * @mbg.generated
     */
    public void setOptype(Integer optype) {
        this.optype = optype;
    }
    
    public static final int fileContentsLen = 51;
    
    public PMsgHttp() {
	}
    
    public PMsgHttp(String[] fileContents) {
    	int index = 0;

		onlyid = fileContents[index ++];
		deviceid = fileContents[index ++];
		index ++;
		try {
			pid = Integer.parseInt(fileContents[index ++]);
		}
		catch (Exception e) {
			e.printStackTrace();
		}
		clientip = fileContents[index ++];
		try {
			clientport = Integer.parseInt(fileContents[index ++]);
		}
		catch (Exception e) {
			e.printStackTrace();
		}
		index ++;
		serverip = fileContents[index ++];
		try {
			serverport = Integer.parseInt(fileContents[index ++]);
		}
		catch (Exception e) {
			e.printStackTrace();
		}
		index ++;
		index ++;
		try {
			timestamp = Integer.parseInt(fileContents[index ++]);
		}
		catch (Exception e) {
			e.printStackTrace();
		}
		index += 21;
		entityfilename = fileContents[index ++];
		pcapfile = fileContents[index ++];
		strurl = fileContents[index ++];
		strmethod = fileContents[index ++];
		strcontenttype = fileContents[index ++];
		szmainfilename = fileContents[index ++];
		sztxtmainfilename = fileContents[index ++];
		szpostfilename = fileContents[index ++];
		strattaname = fileContents[index ++];
		strattafilename = fileContents[index ++];
		strtxtattafilename = fileContents[index ++];
		try {
			affixtype = Integer.parseInt(fileContents[index ++]);
		}
		catch (Exception e) {
			e.printStackTrace();
		}
		try {
			netiproxytype = Integer.parseInt(fileContents[index ++]);
		}
		catch (Exception e) {
			e.printStackTrace();
		}
		strreferer = fileContents[index ++];
		strhost = fileContents[index ++];
		strtitle = fileContents[index ++];
		strcookie = fileContents[index ++];
		try {
			iscomplete = Integer.parseInt(fileContents[index ++]);
		}
		catch (Exception e) {
			e.printStackTrace();
		}
//		strdomain = fileContents[index ++];
//		szreserve = fileContents[index ++];
//		try {
//			behavetype = Integer.parseInt(fileContents[index ++]);
//		}
//		catch (Exception e) {
//			e.printStackTrace();
//		}
//		try {
//			apptype = Integer.parseInt(fileContents[index ++]);
//		}
//		catch (Exception e) {
//			e.printStackTrace();
//		}
//		try {
//			optype = Integer.parseInt(fileContents[index ++]);
//		}
//		catch (Exception e) {
//			e.printStackTrace();
//		}
    }
    
}
