package com.zrt.zenb.entity;

import java.util.List;
import java.util.Map;

import com.zrt.zenb.entity.PMsgSjApp;

public interface PMsgSjAppMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjapp
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjapp
     *
     * @mbg.generated
     */
    int insert(PMsgSjApp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjapp
     *
     * @mbg.generated
     */
    int insertSelective(PMsgSjApp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjapp
     *
     * @mbg.generated
     */
    PMsgSjApp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjapp
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PMsgSjApp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjapp
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PMsgSjApp record);
    
    List<PMsgSjApp> selectSjAppRecord(Map<String, Object> map);
}
